### ISSUE TITLE
molecular.SDF to embedding

### ISSUE THREAD

**Issue by klez1** [guangyunms/BiMoRec#1]
Hello! I'm very interested in your work! After I obtain the output from an SDF file through mol_graph.py, how should I pass it to gvp.py to get the corresponding embeddings? Thank you!

**Comment by guangyunms** [comment]
> Hello! I'm very interested in your work! After I obtain the output from an SDF file through mol_graph.py, how should I pass it to gvp.py to get the corresponding embeddings? Thank you!

First, read data from the sdf file and process it into a graph structure. Then, incorporate a specific model into the pre-training stage, as exemplified by the following model:

`self.drug_model = DrugGVPModel(
            node_in_dim=self.drug_node_in_dim, node_h_dim=self.drug_node_h_dims,
            edge_in_dim=self.drug_edge_in_dim, edge_h_dim=self.drug_edge_h_dims, num_layers=num_layers
        )`

**Comment by guangyunms** [comment]
If you find this project to be helpful, you might consider starring it.

**Comment by klez1** [comment]
Thank you for your reply. I have resolved the issue. Thank you! Your work has been helpful to me!
